/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DIDDocument,
  DIDResolutionResult,
} from '../models';
import {
    DIDDocumentFromJSON,
    DIDDocumentToJSON,
    DIDResolutionResultFromJSON,
    DIDResolutionResultToJSON,
} from '../models';

export interface GetDIDRequest {
    didRef: string;
}

/**
 * 
 */
export class DIDApi extends runtime.BaseAPI {

    /**
     * Resolve Prism DID to a W3C DID document representation. The response can be the [DID resolution result](https://w3c-ccg.github.io/did-resolution/#did-resolution-result) or [DID document representation](https://www.w3.org/TR/did-core/#representations) depending on the `Accept` request header. The response is implemented according to [resolver HTTP binding](https://w3c-ccg.github.io/did-resolution/#bindings-https) in the DID resolution spec. 
     * Resolve Prism DID to a W3C representation
     */
    async getDIDRaw(requestParameters: GetDIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DIDResolutionResult>> {
        if (requestParameters.didRef === null || requestParameters.didRef === undefined) {
            throw new runtime.RequiredError('didRef','Required parameter requestParameters.didRef was null or undefined when calling getDID.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/dids/{didRef}`.replace(`{${"didRef"}}`, encodeURIComponent(String(requestParameters.didRef))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DIDResolutionResultFromJSON(jsonValue));
    }

    /**
     * Resolve Prism DID to a W3C DID document representation. The response can be the [DID resolution result](https://w3c-ccg.github.io/did-resolution/#did-resolution-result) or [DID document representation](https://www.w3.org/TR/did-core/#representations) depending on the `Accept` request header. The response is implemented according to [resolver HTTP binding](https://w3c-ccg.github.io/did-resolution/#bindings-https) in the DID resolution spec. 
     * Resolve Prism DID to a W3C representation
     */
    async getDID(requestParameters: GetDIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DIDResolutionResult> {
        const response = await this.getDIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
