/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptCredentialOfferRequest,
  CreateIssueCredentialRecordRequest,
  ErrorResponse,
  IssueCredentialRecord,
  IssueCredentialRecordPage,
} from '../models';
import {
    AcceptCredentialOfferRequestFromJSON,
    AcceptCredentialOfferRequestToJSON,
    CreateIssueCredentialRecordRequestFromJSON,
    CreateIssueCredentialRecordRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    IssueCredentialRecordFromJSON,
    IssueCredentialRecordToJSON,
    IssueCredentialRecordPageFromJSON,
    IssueCredentialRecordPageToJSON,
} from '../models';

export interface AcceptCredentialOfferOperationRequest {
    recordId: string;
    acceptCredentialOfferRequest: AcceptCredentialOfferRequest;
}

export interface CreateCredentialOfferRequest {
    createIssueCredentialRecordRequest: CreateIssueCredentialRecordRequest;
}

export interface GetCredentialRecordRequest {
    recordId: string;
}

export interface GetCredentialRecordsRequest {
    offset?: number;
    limit?: number;
    thid?: string;
}

export interface IssueCredentialRequest {
    recordId: string;
}

/**
 * 
 */
export class IssueCredentialsProtocolApi extends runtime.BaseAPI {

    /**
     * Accepts a credential offer received from a VC issuer and sends back a credential request.
     * As a holder, accepts a credential offer received from an issuer.
     */
    async acceptCredentialOfferRaw(requestParameters: AcceptCredentialOfferOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueCredentialRecord>> {
        if (requestParameters.recordId === null || requestParameters.recordId === undefined) {
            throw new runtime.RequiredError('recordId','Required parameter requestParameters.recordId was null or undefined when calling acceptCredentialOffer.');
        }

        if (requestParameters.acceptCredentialOfferRequest === null || requestParameters.acceptCredentialOfferRequest === undefined) {
            throw new runtime.RequiredError('acceptCredentialOfferRequest','Required parameter requestParameters.acceptCredentialOfferRequest was null or undefined when calling acceptCredentialOffer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/issue-credentials/records/{recordId}/accept-offer`.replace(`{${"recordId"}}`, encodeURIComponent(String(requestParameters.recordId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptCredentialOfferRequestToJSON(requestParameters.acceptCredentialOfferRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCredentialRecordFromJSON(jsonValue));
    }

    /**
     * Accepts a credential offer received from a VC issuer and sends back a credential request.
     * As a holder, accepts a credential offer received from an issuer.
     */
    async acceptCredentialOffer(requestParameters: AcceptCredentialOfferOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueCredentialRecord> {
        const response = await this.acceptCredentialOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new credential offer in the database
     * As a credential issuer, create a new credential offer to be sent to a holder.
     */
    async createCredentialOfferRaw(requestParameters: CreateCredentialOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueCredentialRecord>> {
        if (requestParameters.createIssueCredentialRecordRequest === null || requestParameters.createIssueCredentialRecordRequest === undefined) {
            throw new runtime.RequiredError('createIssueCredentialRecordRequest','Required parameter requestParameters.createIssueCredentialRecordRequest was null or undefined when calling createCredentialOffer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/issue-credentials/credential-offers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIssueCredentialRecordRequestToJSON(requestParameters.createIssueCredentialRecordRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCredentialRecordFromJSON(jsonValue));
    }

    /**
     * Creates a new credential offer in the database
     * As a credential issuer, create a new credential offer to be sent to a holder.
     */
    async createCredentialOffer(requestParameters: CreateCredentialOfferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueCredentialRecord> {
        const response = await this.createCredentialOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets issue credential records by record id
     * Gets an existing issue credential record by its unique identifier.
     */
    async getCredentialRecordRaw(requestParameters: GetCredentialRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueCredentialRecord>> {
        if (requestParameters.recordId === null || requestParameters.recordId === undefined) {
            throw new runtime.RequiredError('recordId','Required parameter requestParameters.recordId was null or undefined when calling getCredentialRecord.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/issue-credentials/records/{recordId}`.replace(`{${"recordId"}}`, encodeURIComponent(String(requestParameters.recordId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCredentialRecordFromJSON(jsonValue));
    }

    /**
     * Gets issue credential records by record id
     * Gets an existing issue credential record by its unique identifier.
     */
    async getCredentialRecord(requestParameters: GetCredentialRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueCredentialRecord> {
        const response = await this.getCredentialRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the list of issue credential records paginated
     * Gets the list of issue credential records.
     */
    async getCredentialRecordsRaw(requestParameters: GetCredentialRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueCredentialRecordPage>> {
        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.thid !== undefined) {
            queryParameters['thid'] = requestParameters.thid;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/issue-credentials/records`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCredentialRecordPageFromJSON(jsonValue));
    }

    /**
     * Get the list of issue credential records paginated
     * Gets the list of issue credential records.
     */
    async getCredentialRecords(requestParameters: GetCredentialRecordsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueCredentialRecordPage> {
        const response = await this.getCredentialRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sends credential to a holder (holder DID is specified in credential as subjectDid). Credential is constructed from the credential records found by credential id.
     * As an issuer, issues the verifiable credential related to the specified record.
     */
    async issueCredentialRaw(requestParameters: IssueCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IssueCredentialRecord>> {
        if (requestParameters.recordId === null || requestParameters.recordId === undefined) {
            throw new runtime.RequiredError('recordId','Required parameter requestParameters.recordId was null or undefined when calling issueCredential.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/issue-credentials/records/{recordId}/issue-credential`.replace(`{${"recordId"}}`, encodeURIComponent(String(requestParameters.recordId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IssueCredentialRecordFromJSON(jsonValue));
    }

    /**
     * Sends credential to a holder (holder DID is specified in credential as subjectDid). Credential is constructed from the credential records found by credential id.
     * As an issuer, issues the verifiable credential related to the specified record.
     */
    async issueCredential(requestParameters: IssueCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IssueCredentialRecord> {
        const response = await this.issueCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
