/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PresentationStatus,
  PresentationStatusPage,
  RequestPresentationAction,
  RequestPresentationInput,
  RequestPresentationOutput,
} from '../models';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PresentationStatusFromJSON,
    PresentationStatusToJSON,
    PresentationStatusPageFromJSON,
    PresentationStatusPageToJSON,
    RequestPresentationActionFromJSON,
    RequestPresentationActionToJSON,
    RequestPresentationInputFromJSON,
    RequestPresentationInputToJSON,
    RequestPresentationOutputFromJSON,
    RequestPresentationOutputToJSON,
} from '../models';

export interface GetAllPresentationRequest {
    offset?: number;
    limit?: number;
    thid?: string;
}

export interface GetPresentationRequest {
    presentationId: string;
}

export interface RequestPresentationRequest {
    requestPresentationInput: RequestPresentationInput;
}

export interface UpdatePresentationRequest {
    presentationId: string;
    requestPresentationAction: RequestPresentationAction;
}

/**
 * 
 */
export class PresentProofApi extends runtime.BaseAPI {

    /**
     * list of presentation statuses
     * Gets the list of proof presentation records.
     */
    async getAllPresentationRaw(requestParameters: GetAllPresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresentationStatusPage>> {
        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.thid !== undefined) {
            queryParameters['thid'] = requestParameters.thid;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/present-proof/presentations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresentationStatusPageFromJSON(jsonValue));
    }

    /**
     * list of presentation statuses
     * Gets the list of proof presentation records.
     */
    async getAllPresentation(requestParameters: GetAllPresentationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresentationStatusPage> {
        const response = await this.getAllPresentationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns an existing presentation record by id.
     * Gets an existing proof presentation record by its unique identifier. More information on the error can be found in the response body.
     */
    async getPresentationRaw(requestParameters: GetPresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresentationStatus>> {
        if (requestParameters.presentationId === null || requestParameters.presentationId === undefined) {
            throw new runtime.RequiredError('presentationId','Required parameter requestParameters.presentationId was null or undefined when calling getPresentation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/present-proof/presentations/{presentationId}`.replace(`{${"presentationId"}}`, encodeURIComponent(String(requestParameters.presentationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresentationStatusFromJSON(jsonValue));
    }

    /**
     * Returns an existing presentation record by id.
     * Gets an existing proof presentation record by its unique identifier. More information on the error can be found in the response body.
     */
    async getPresentation(requestParameters: GetPresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresentationStatus> {
        const response = await this.getPresentationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Holder presents proof derived from the verifiable credential to verifier.
     * As a Verifier, create a new proof presentation request and send it to the Prover.
     */
    async requestPresentationRaw(requestParameters: RequestPresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestPresentationOutput>> {
        if (requestParameters.requestPresentationInput === null || requestParameters.requestPresentationInput === undefined) {
            throw new runtime.RequiredError('requestPresentationInput','Required parameter requestParameters.requestPresentationInput was null or undefined when calling requestPresentation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/present-proof/presentations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestPresentationInputToJSON(requestParameters.requestPresentationInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestPresentationOutputFromJSON(jsonValue));
    }

    /**
     * Holder presents proof derived from the verifiable credential to verifier.
     * As a Verifier, create a new proof presentation request and send it to the Prover.
     */
    async requestPresentation(requestParameters: RequestPresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestPresentationOutput> {
        const response = await this.requestPresentationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accept or reject presentation of proof request.
     * Updates the proof presentation record matching the unique identifier, with the specific action to perform.
     */
    async updatePresentationRaw(requestParameters: UpdatePresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresentationStatus>> {
        if (requestParameters.presentationId === null || requestParameters.presentationId === undefined) {
            throw new runtime.RequiredError('presentationId','Required parameter requestParameters.presentationId was null or undefined when calling updatePresentation.');
        }

        if (requestParameters.requestPresentationAction === null || requestParameters.requestPresentationAction === undefined) {
            throw new runtime.RequiredError('requestPresentationAction','Required parameter requestParameters.requestPresentationAction was null or undefined when calling updatePresentation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/present-proof/presentations/{presentationId}`.replace(`{${"presentationId"}}`, encodeURIComponent(String(requestParameters.presentationId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RequestPresentationActionToJSON(requestParameters.requestPresentationAction),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresentationStatusFromJSON(jsonValue));
    }

    /**
     * Accept or reject presentation of proof request.
     * Updates the proof presentation record matching the unique identifier, with the specific action to perform.
     */
    async updatePresentation(requestParameters: UpdatePresentationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresentationStatus> {
        const response = await this.updatePresentationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
