version: "3.0"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./config/jupyter-config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
      - ./config:/home/jovyan/.jupyter/config
