/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptConnectionInvitationRequest
 */
export interface AcceptConnectionInvitationRequest {
    /**
     * The base64-encoded raw invitation.
     * @type {string}
     * @memberof AcceptConnectionInvitationRequest
     */
    invitation: string;
}

/**
 * Check if a given object implements the AcceptConnectionInvitationRequest interface.
 */
export function instanceOfAcceptConnectionInvitationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "invitation" in value;

    return isInstance;
}

export function AcceptConnectionInvitationRequestFromJSON(json: any): AcceptConnectionInvitationRequest {
    return AcceptConnectionInvitationRequestFromJSONTyped(json, false);
}

export function AcceptConnectionInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptConnectionInvitationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invitation': json['invitation'],
    };
}

export function AcceptConnectionInvitationRequestToJSON(value?: AcceptConnectionInvitationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invitation': value.invitation,
    };
}

