/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Arr
 */
export interface Arr {
    /**
     * 
     * @type {Array<any>}
     * @memberof Arr
     */
    elements?: Array<any>;
}

/**
 * Check if a given object implements the Arr interface.
 */
export function instanceOfArr(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArrFromJSON(json: any): Arr {
    return ArrFromJSONTyped(json, false);
}

export function ArrFromJSONTyped(json: any, ignoreDiscriminator: boolean): Arr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elements': !exists(json, 'elements') ? undefined : json['elements'],
    };
}

export function ArrToJSON(value?: Arr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elements': value.elements,
    };
}

