/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConnectionInvitation } from './ConnectionInvitation';
import {
    ConnectionInvitationFromJSON,
    ConnectionInvitationFromJSONTyped,
    ConnectionInvitationToJSON,
} from './ConnectionInvitation';

/**
 * 
 * @export
 * @interface Connection
 */
export interface Connection {
    /**
     * The unique identifier of the connection.
     * @type {string}
     * @memberof Connection
     */
    connectionId: string;
    /**
     * A human readable alias for the connection.
     * @type {string}
     * @memberof Connection
     */
    label?: string;
    /**
     * The DID representing me as the inviter or invitee in this specific connection.
     * @type {string}
     * @memberof Connection
     */
    myDid?: string;
    /**
     * The DID representing the other peer as the an inviter or invitee in this specific connection.
     * @type {string}
     * @memberof Connection
     */
    theirDid?: string;
    /**
     * The role played by the Prism agent in the connection flow.
     * @type {string}
     * @memberof Connection
     */
    role: ConnectionRoleEnum;
    /**
     * The current state of the connection protocol execution.
     * @type {string}
     * @memberof Connection
     */
    state: ConnectionStateEnum;
    /**
     * 
     * @type {ConnectionInvitation}
     * @memberof Connection
     */
    invitation: ConnectionInvitation;
    /**
     * The date and time the connection record was created.
     * @type {Date}
     * @memberof Connection
     */
    createdAt: Date;
    /**
     * The date and time the connection record was last updated.
     * @type {Date}
     * @memberof Connection
     */
    updatedAt?: Date;
    /**
     * The reference to the connection resource.
     * @type {string}
     * @memberof Connection
     */
    self: string;
    /**
     * The type of object returned. In this case a `Connection`.
     * @type {string}
     * @memberof Connection
     */
    kind: string;
}


/**
 * @export
 */
export const ConnectionRoleEnum = {
    Inviter: 'Inviter',
    Invitee: 'Invitee'
} as const;
export type ConnectionRoleEnum = typeof ConnectionRoleEnum[keyof typeof ConnectionRoleEnum];

/**
 * @export
 */
export const ConnectionStateEnum = {
    InvitationGenerated: 'InvitationGenerated',
    InvitationReceived: 'InvitationReceived',
    ConnectionRequestPending: 'ConnectionRequestPending',
    ConnectionRequestSent: 'ConnectionRequestSent',
    ConnectionRequestReceived: 'ConnectionRequestReceived',
    ConnectionResponsePending: 'ConnectionResponsePending',
    ConnectionResponseSent: 'ConnectionResponseSent',
    ConnectionResponseReceived: 'ConnectionResponseReceived',
    ProblemReportPending: 'ProblemReportPending',
    ProblemReportSent: 'ProblemReportSent',
    ProblemReportReceived: 'ProblemReportReceived'
} as const;
export type ConnectionStateEnum = typeof ConnectionStateEnum[keyof typeof ConnectionStateEnum];


/**
 * Check if a given object implements the Connection interface.
 */
export function instanceOfConnection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "connectionId" in value;
    isInstance = isInstance && "role" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "invitation" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "self" in value;
    isInstance = isInstance && "kind" in value;

    return isInstance;
}

export function ConnectionFromJSON(json: any): Connection {
    return ConnectionFromJSONTyped(json, false);
}

export function ConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Connection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'myDid': !exists(json, 'myDid') ? undefined : json['myDid'],
        'theirDid': !exists(json, 'theirDid') ? undefined : json['theirDid'],
        'role': json['role'],
        'state': json['state'],
        'invitation': ConnectionInvitationFromJSON(json['invitation']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'self': json['self'],
        'kind': json['kind'],
    };
}

export function ConnectionToJSON(value?: Connection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connectionId': value.connectionId,
        'label': value.label,
        'myDid': value.myDid,
        'theirDid': value.theirDid,
        'role': value.role,
        'state': value.state,
        'invitation': ConnectionInvitationToJSON(value.invitation),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'self': value.self,
        'kind': value.kind,
    };
}

