/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The invitation for this connection
 * @export
 * @interface ConnectionInvitation
 */
export interface ConnectionInvitation {
    /**
     * The unique identifier of the invitation. It should be used as parent thread ID (pthid) for the Connection Request message that follows.
     * @type {string}
     * @memberof ConnectionInvitation
     */
    id: string;
    /**
     * The DIDComm Message Type URI (MTURI) the invitation message complies with.
     * @type {string}
     * @memberof ConnectionInvitation
     */
    type: string;
    /**
     * The DID representing the sender to be used by recipients for future interactions.
     * @type {string}
     * @memberof ConnectionInvitation
     */
    from: string;
    /**
     * The invitation message encoded as a URL. This URL follows the Out of [Band 2.0 protocol](https://identity.foundation/didcomm-messaging/spec/v2.0/#out-of-band-messages) and can be used to generate a QR code for example.
     * @type {string}
     * @memberof ConnectionInvitation
     */
    invitationUrl: string;
}

/**
 * Check if a given object implements the ConnectionInvitation interface.
 */
export function instanceOfConnectionInvitation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "invitationUrl" in value;

    return isInstance;
}

export function ConnectionInvitationFromJSON(json: any): ConnectionInvitation {
    return ConnectionInvitationFromJSONTyped(json, false);
}

export function ConnectionInvitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionInvitation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'from': json['from'],
        'invitationUrl': json['invitationUrl'],
    };
}

export function ConnectionInvitationToJSON(value?: ConnectionInvitation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'from': value.from,
        'invitationUrl': value.invitationUrl,
    };
}

