/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConnectionRequest
 */
export interface CreateConnectionRequest {
    /**
     * A human readable alias for the connection.
     * @type {string}
     * @memberof CreateConnectionRequest
     */
    label?: string;
}

/**
 * Check if a given object implements the CreateConnectionRequest interface.
 */
export function instanceOfCreateConnectionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateConnectionRequestFromJSON(json: any): CreateConnectionRequest {
    return CreateConnectionRequestFromJSONTyped(json, false);
}

export function CreateConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConnectionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : json['label'],
    };
}

export function CreateConnectionRequestToJSON(value?: CreateConnectionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
    };
}

