/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CredentialSchemaResponse } from './CredentialSchemaResponse';
import {
    CredentialSchemaResponseFromJSON,
    CredentialSchemaResponseFromJSONTyped,
    CredentialSchemaResponseToJSON,
} from './CredentialSchemaResponse';

/**
 * 
 * @export
 * @interface CredentialSchemaResponsePage
 */
export interface CredentialSchemaResponsePage {
    /**
     * A sequence of CredentialSchemaResponse objects representing the list of credential schemas that the API response contains
     * @type {Array<CredentialSchemaResponse>}
     * @memberof CredentialSchemaResponsePage
     */
    contents?: Array<CredentialSchemaResponse>;
    /**
     * A string field indicating the type of the API response. In this case, it will always be set to `CredentialSchemaPage`
     * @type {string}
     * @memberof CredentialSchemaResponsePage
     */
    kind: string;
    /**
     * A string field containing the URL of the current API endpoint
     * @type {string}
     * @memberof CredentialSchemaResponsePage
     */
    self: string;
    /**
     * A string field indicating the type of resource that the contents field contains
     * @type {string}
     * @memberof CredentialSchemaResponsePage
     */
    pageOf: string;
    /**
     * An optional string field containing the URL of the next page of results. If the API response does not contain any more pages, this field should be set to None.
     * @type {string}
     * @memberof CredentialSchemaResponsePage
     */
    next?: string;
    /**
     * An optional string field containing the URL of the previous page of results. If the API response is the first page of results, this field should be set to None.
     * @type {string}
     * @memberof CredentialSchemaResponsePage
     */
    previous?: string;
}

/**
 * Check if a given object implements the CredentialSchemaResponsePage interface.
 */
export function instanceOfCredentialSchemaResponsePage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "self" in value;
    isInstance = isInstance && "pageOf" in value;

    return isInstance;
}

export function CredentialSchemaResponsePageFromJSON(json: any): CredentialSchemaResponsePage {
    return CredentialSchemaResponsePageFromJSONTyped(json, false);
}

export function CredentialSchemaResponsePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialSchemaResponsePage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': !exists(json, 'contents') ? undefined : ((json['contents'] as Array<any>).map(CredentialSchemaResponseFromJSON)),
        'kind': json['kind'],
        'self': json['self'],
        'pageOf': json['pageOf'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
    };
}

export function CredentialSchemaResponsePageToJSON(value?: CredentialSchemaResponsePage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': value.contents === undefined ? undefined : ((value.contents as Array<any>).map(CredentialSchemaResponseToJSON)),
        'kind': value.kind,
        'self': value.self,
        'pageOf': value.pageOf,
        'next': value.next,
        'previous': value.previous,
    };
}

