/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * [DID document metadata](https://www.w3.org/TR/did-core/#did-document-metadata)
 * @export
 * @interface DIDDocumentMetadata
 */
export interface DIDDocumentMetadata {
    /**
     * If a DID has been deactivated, DID document metadata MUST include this property with the boolean value true. If a DID has not been deactivated, this property is OPTIONAL, but if included, MUST have the boolean value false.
     * @type {boolean}
     * @memberof DIDDocumentMetadata
     */
    deactivated?: boolean;
    /**
     * 
     * A DID in canonical form.
     * If a DID is in long form and has been published, DID document metadata MUST contain a `canonicalId`` property with the short form DID as its value.
     * If a DID in short form or has not been published, DID document metadata MUST NOT contain a `canonicalId` property.
     * @type {string}
     * @memberof DIDDocumentMetadata
     */
    canonicalId?: string;
    /**
     * 
     * DID document metadata MUST contain a versionId property with the hash of the AtalaOperation contained in the latest valid SignedAtalaOperation that created the DID or changed the DID's internal state.
     * @type {string}
     * @memberof DIDDocumentMetadata
     */
    versionId?: string;
    /**
     * The timestamp of the Cardano block that contained the first valid SignedAtalaOperation with a CreateDIDOperation that created the DID.
     * @type {string}
     * @memberof DIDDocumentMetadata
     */
    created?: string;
    /**
     * The timestamp of the Cardano block that contained the latest valid SignedAtalaOperation that changed the DID's internal state.
     * @type {string}
     * @memberof DIDDocumentMetadata
     */
    updated?: string;
}

/**
 * Check if a given object implements the DIDDocumentMetadata interface.
 */
export function instanceOfDIDDocumentMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DIDDocumentMetadataFromJSON(json: any): DIDDocumentMetadata {
    return DIDDocumentMetadataFromJSONTyped(json, false);
}

export function DIDDocumentMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DIDDocumentMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deactivated': !exists(json, 'deactivated') ? undefined : json['deactivated'],
        'canonicalId': !exists(json, 'canonicalId') ? undefined : json['canonicalId'],
        'versionId': !exists(json, 'versionId') ? undefined : json['versionId'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
    };
}

export function DIDDocumentMetadataToJSON(value?: DIDDocumentMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deactivated': value.deactivated,
        'canonicalId': value.canonicalId,
        'versionId': value.versionId,
        'created': value.created,
        'updated': value.updated,
    };
}

