/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IssueCredentialRecord } from './IssueCredentialRecord';
import {
    IssueCredentialRecordFromJSON,
    IssueCredentialRecordFromJSONTyped,
    IssueCredentialRecordToJSON,
} from './IssueCredentialRecord';

/**
 * 
 * @export
 * @interface IssueCredentialRecordPage
 */
export interface IssueCredentialRecordPage {
    /**
     * A string field containing the URL of the current API endpoint
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    self: string;
    /**
     * A string field containing the URL of the current API endpoint
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    kind: string;
    /**
     * A string field indicating the type of resource that the contents field contains
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    pageOf: string;
    /**
     * An optional string field containing the URL of the next page of results. If the API response does not contain any more pages, this field should be set to None.
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    next?: string;
    /**
     * An optional string field containing the URL of the previous page of results. If the API response is the first page of results, this field should be set to None.
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    previous?: string;
    /**
     * A sequence of IssueCredentialRecord objects representing the list of credential records that the API response contains
     * @type {Array<IssueCredentialRecord>}
     * @memberof IssueCredentialRecordPage
     */
    contents?: Array<IssueCredentialRecord>;
}

/**
 * Check if a given object implements the IssueCredentialRecordPage interface.
 */
export function instanceOfIssueCredentialRecordPage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "self" in value;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "pageOf" in value;

    return isInstance;
}

export function IssueCredentialRecordPageFromJSON(json: any): IssueCredentialRecordPage {
    return IssueCredentialRecordPageFromJSONTyped(json, false);
}

export function IssueCredentialRecordPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCredentialRecordPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': json['self'],
        'kind': json['kind'],
        'pageOf': json['pageOf'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'contents': !exists(json, 'contents') ? undefined : ((json['contents'] as Array<any>).map(IssueCredentialRecordFromJSON)),
    };
}

export function IssueCredentialRecordPageToJSON(value?: IssueCredentialRecordPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
        'kind': value.kind,
        'pageOf': value.pageOf,
        'next': value.next,
        'previous': value.previous,
        'contents': value.contents === undefined ? undefined : ((value.contents as Array<any>).map(IssueCredentialRecordToJSON)),
    };
}

