/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Purpose } from './Purpose';
import {
    PurposeFromJSON,
    PurposeFromJSONTyped,
    PurposeToJSON,
} from './Purpose';

/**
 * key-pair template to add to DID document.
 * @export
 * @interface ManagedDIDKeyTemplate
 */
export interface ManagedDIDKeyTemplate {
    /**
     * Identifier of a verification material in the DID Document
     * @type {string}
     * @memberof ManagedDIDKeyTemplate
     */
    id: string;
    /**
     * 
     * @type {Purpose}
     * @memberof ManagedDIDKeyTemplate
     */
    purpose: Purpose;
}

/**
 * Check if a given object implements the ManagedDIDKeyTemplate interface.
 */
export function instanceOfManagedDIDKeyTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "purpose" in value;

    return isInstance;
}

export function ManagedDIDKeyTemplateFromJSON(json: any): ManagedDIDKeyTemplate {
    return ManagedDIDKeyTemplateFromJSONTyped(json, false);
}

export function ManagedDIDKeyTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedDIDKeyTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'purpose': PurposeFromJSON(json['purpose']),
    };
}

export function ManagedDIDKeyTemplateToJSON(value?: ManagedDIDKeyTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'purpose': PurposeToJSON(value.purpose),
    };
}

