/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Num
 */
export interface Num {
    /**
     * 
     * @type {number}
     * @memberof Num
     */
    value: number;
}

/**
 * Check if a given object implements the Num interface.
 */
export function instanceOfNum(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function NumFromJSON(json: any): Num {
    return NumFromJSONTyped(json, false);
}

export function NumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Num {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function NumToJSON(value?: Num | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

