/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The options to use when creating the proof presentation request (e.g., domain, challenge).
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * The challenge should be a randomly generated string.
     * @type {string}
     * @memberof Options
     */
    challenge: string;
    /**
     * The domain value can be any string or URI.
     * @type {string}
     * @memberof Options
     */
    domain: string;
}

/**
 * Check if a given object implements the Options interface.
 */
export function instanceOfOptions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "challenge" in value;
    isInstance = isInstance && "domain" in value;

    return isInstance;
}

export function OptionsFromJSON(json: any): Options {
    return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'domain': json['domain'],
    };
}

export function OptionsToJSON(value?: Options | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'challenge': value.challenge,
        'domain': value.domain,
    };
}

