/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Purpose of the verification material in the DID Document
 * @export
 */
export const Purpose = {
    AssertionMethod: 'assertionMethod',
    Authentication: 'authentication',
    CapabilityDelegation: 'capabilityDelegation',
    CapabilityInvocation: 'capabilityInvocation',
    KeyAgreement: 'keyAgreement'
} as const;
export type Purpose = typeof Purpose[keyof typeof Purpose];


export function PurposeFromJSON(json: any): Purpose {
    return PurposeFromJSONTyped(json, false);
}

export function PurposeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Purpose {
    return json as Purpose;
}

export function PurposeToJSON(value?: Purpose | null): any {
    return value as any;
}

