/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveEntryById
 */
export interface RemoveEntryById {
    /**
     * 
     * @type {string}
     * @memberof RemoveEntryById
     */
    id: string;
}

/**
 * Check if a given object implements the RemoveEntryById interface.
 */
export function instanceOfRemoveEntryById(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function RemoveEntryByIdFromJSON(json: any): RemoveEntryById {
    return RemoveEntryByIdFromJSONTyped(json, false);
}

export function RemoveEntryByIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveEntryById {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function RemoveEntryByIdToJSON(value?: RemoveEntryById | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

