/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Options } from './Options';
import {
    OptionsFromJSON,
    OptionsFromJSONTyped,
    OptionsToJSON,
} from './Options';
import type { ProofRequestAux } from './ProofRequestAux';
import {
    ProofRequestAuxFromJSON,
    ProofRequestAuxFromJSONTyped,
    ProofRequestAuxToJSON,
} from './ProofRequestAux';

/**
 * 
 * @export
 * @interface RequestPresentationInput
 */
export interface RequestPresentationInput {
    /**
     * The unique identifier of an established connection between the verifier and the prover.
     * @type {string}
     * @memberof RequestPresentationInput
     */
    connectionId: string;
    /**
     * 
     * @type {Options}
     * @memberof RequestPresentationInput
     */
    options?: Options;
    /**
     * The type of proofs requested in the context of this proof presentation request (e.g., VC schema, trusted issuers, etc.)
     * @type {Array<ProofRequestAux>}
     * @memberof RequestPresentationInput
     */
    proofs?: Array<ProofRequestAux>;
}

/**
 * Check if a given object implements the RequestPresentationInput interface.
 */
export function instanceOfRequestPresentationInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "connectionId" in value;

    return isInstance;
}

export function RequestPresentationInputFromJSON(json: any): RequestPresentationInput {
    return RequestPresentationInputFromJSONTyped(json, false);
}

export function RequestPresentationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPresentationInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'options': !exists(json, 'options') ? undefined : OptionsFromJSON(json['options']),
        'proofs': !exists(json, 'proofs') ? undefined : ((json['proofs'] as Array<any>).map(ProofRequestAuxFromJSON)),
    };
}

export function RequestPresentationInputToJSON(value?: RequestPresentationInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connectionId': value.connectionId,
        'options': OptionsToJSON(value.options),
        'proofs': value.proofs === undefined ? undefined : ((value.proofs as Array<any>).map(ProofRequestAuxToJSON)),
    };
}

