/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A service expressed in the DID document. https://www.w3.org/TR/did-core/#services
 * @export
 * @interface Service
 */
export interface Service {
    /**
     * The id of the service.
     * Requires a URI fragment when use in create / update DID.
     * Returns the full ID (with DID prefix) when resolving DID
     * @type {string}
     * @memberof Service
     */
    id: string;
    /**
     * Service type. Can contain multiple possible values as described in the [Create DID operation](https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md#create-did) under the construction section.
     * @type {string}
     * @memberof Service
     */
    type: string;
    /**
     * The service endpoint. Can contain multiple possible values as described in the [Create DID operation]
     * @type {Array<string>}
     * @memberof Service
     */
    serviceEndpoint: Array<string>;
}

/**
 * Check if a given object implements the Service interface.
 */
export function instanceOfService(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "serviceEndpoint" in value;

    return isInstance;
}

export function ServiceFromJSON(json: any): Service {
    return ServiceFromJSONTyped(json, false);
}

export function ServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Service {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'serviceEndpoint': json['serviceEndpoint'],
    };
}

export function ServiceToJSON(value?: Service | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'serviceEndpoint': value.serviceEndpoint,
    };
}

