/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Str
 */
export interface Str {
    /**
     * 
     * @type {string}
     * @memberof Str
     */
    value: string;
}

/**
 * Check if a given object implements the Str interface.
 */
export function instanceOfStr(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function StrFromJSON(json: any): Str {
    return StrFromJSONTyped(json, false);
}

export function StrFromJSONTyped(json: any, ignoreDiscriminator: boolean): Str {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function StrToJSON(value?: Str | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

