/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type UpdateManagedDIDServiceActionType
 * The type of the service
 * @export
 */
export type UpdateManagedDIDServiceActionType = Array<string> | string;

export function UpdateManagedDIDServiceActionTypeFromJSON(json: any): UpdateManagedDIDServiceActionType {
    return UpdateManagedDIDServiceActionTypeFromJSONTyped(json, false);
}

export function UpdateManagedDIDServiceActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDServiceActionType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Array<string>FromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function UpdateManagedDIDServiceActionTypeToJSON(value?: UpdateManagedDIDServiceActionType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfArray<string>(value)) {
        return Array<string>ToJSON(value as Array<string>);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

