/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateManagedDIDRequestAction } from './UpdateManagedDIDRequestAction';
import {
    UpdateManagedDIDRequestActionFromJSON,
    UpdateManagedDIDRequestActionFromJSONTyped,
    UpdateManagedDIDRequestActionToJSON,
} from './UpdateManagedDIDRequestAction';

/**
 * 
 * @export
 * @interface UpdateManagedDIDRequest
 */
export interface UpdateManagedDIDRequest {
    /**
     * 
     * @type {Array<UpdateManagedDIDRequestAction>}
     * @memberof UpdateManagedDIDRequest
     */
    actions?: Array<UpdateManagedDIDRequestAction>;
}

/**
 * Check if a given object implements the UpdateManagedDIDRequest interface.
 */
export function instanceOfUpdateManagedDIDRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateManagedDIDRequestFromJSON(json: any): UpdateManagedDIDRequest {
    return UpdateManagedDIDRequestFromJSONTyped(json, false);
}

export function UpdateManagedDIDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actions': !exists(json, 'actions') ? undefined : ((json['actions'] as Array<any>).map(UpdateManagedDIDRequestActionFromJSON)),
    };
}

export function UpdateManagedDIDRequestToJSON(value?: UpdateManagedDIDRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actions': value.actions === undefined ? undefined : ((value.actions as Array<any>).map(UpdateManagedDIDRequestActionToJSON)),
    };
}

