/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A patch to existing Service. 'type' and 'serviceEndpoint' cannot both be empty.
 * @export
 * @interface UpdateManagedDIDServiceAction
 */
export interface UpdateManagedDIDServiceAction {
    /**
     * The id of the service to update
     * @type {string}
     * @memberof UpdateManagedDIDServiceAction
     */
    id: string;
    /**
     * The type of the service
     * @type {string}
     * @memberof UpdateManagedDIDServiceAction
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateManagedDIDServiceAction
     */
    serviceEndpoint?: Array<string>;
}

/**
 * Check if a given object implements the UpdateManagedDIDServiceAction interface.
 */
export function instanceOfUpdateManagedDIDServiceAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateManagedDIDServiceActionFromJSON(json: any): UpdateManagedDIDServiceAction {
    return UpdateManagedDIDServiceActionFromJSONTyped(json, false);
}

export function UpdateManagedDIDServiceActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDServiceAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'serviceEndpoint': !exists(json, 'serviceEndpoint') ? undefined : json['serviceEndpoint'],
    };
}

export function UpdateManagedDIDServiceActionToJSON(value?: UpdateManagedDIDServiceAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'serviceEndpoint': value.serviceEndpoint,
    };
}

