/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerificationPolicyConstraint
 */
export interface VerificationPolicyConstraint {
    /**
     * 
     * @type {string}
     * @memberof VerificationPolicyConstraint
     */
    schemaId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof VerificationPolicyConstraint
     */
    trustedIssuers?: Array<string>;
}

/**
 * Check if a given object implements the VerificationPolicyConstraint interface.
 */
export function instanceOfVerificationPolicyConstraint(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "schemaId" in value;

    return isInstance;
}

export function VerificationPolicyConstraintFromJSON(json: any): VerificationPolicyConstraint {
    return VerificationPolicyConstraintFromJSONTyped(json, false);
}

export function VerificationPolicyConstraintFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationPolicyConstraint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schemaId': json['schemaId'],
        'trustedIssuers': !exists(json, 'trustedIssuers') ? undefined : json['trustedIssuers'],
    };
}

export function VerificationPolicyConstraintToJSON(value?: VerificationPolicyConstraint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schemaId': value.schemaId,
        'trustedIssuers': value.trustedIssuers,
    };
}

